2025-08-18 11:08:13,042 - dashboard_app - logger_setup:setup_logger:43 - INFO - 服务启动，日志存储目录：Logger/20250818_110813
2025-08-18 11:08:13,160 - dashboard_app - cache_manager:_load_offline_cache:28 - INFO - 成功加载离线缓存，包含 1 个文件缓存
2025-08-18 11:08:25,679 - dashboard_app - app:_load_data:57 - INFO - 从离线缓存加载文件: all_sequence_HLX14B178R0001811_merged.csv
2025-08-18 11:08:37,961 - dashboard_app - navigation_knowledge_graph:process_data:46 - ERROR - 构建知识图谱失败: local variable 'temp_filename' referenced before assignment
Traceback (most recent call last):
  File "/Users/lichen18/Documents/Project/demo/Handle_csv/scenario/navigation/knowledge_graph.py", line 234, in generate_visualization
    with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.html') as tmp:
NameError: name 'tempfile' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lichen18/Documents/Project/demo/modules/navigation_knowledge_graph.py", line 40, in process_data
    self.visualization_buf = self.kg.generate_visualization()
  File "/Users/lichen18/Documents/Project/demo/Handle_csv/scenario/navigation/knowledge_graph.py", line 249, in generate_visualization
    if os.path.exists(temp_filename):
UnboundLocalError: local variable 'temp_filename' referenced before assignment
2025-08-18 11:08:38,430 - dashboard_app - navigation_knowledge_graph:process_data:46 - ERROR - 构建知识图谱失败: local variable 'temp_filename' referenced before assignment
Traceback (most recent call last):
  File "/Users/lichen18/Documents/Project/demo/Handle_csv/scenario/navigation/knowledge_graph.py", line 234, in generate_visualization
    with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.html') as tmp:
NameError: name 'tempfile' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lichen18/Documents/Project/demo/modules/navigation_knowledge_graph.py", line 40, in process_data
    self.visualization_buf = self.kg.generate_visualization()
  File "/Users/lichen18/Documents/Project/demo/Handle_csv/scenario/navigation/knowledge_graph.py", line 249, in generate_visualization
    if os.path.exists(temp_filename):
UnboundLocalError: local variable 'temp_filename' referenced before assignment
